

export let icon = (name) => {
    const iconMap = {
        // 🌾 Crops / Grains
       rice: "🌾",
        wheat: "🌾",
        maize: "🌽",
        corn: "🌽",
        barley: "🌾",
        millet: "🌾",
        oats: "🌾",
        sorghum: "🌾",
        rye: "🌾",
        quinoa: "🌾",
        buckwheat: "🌾",

        // 🫘 Pulses / Legumes
        chickpea: "🫘",
        lentil: "🫘",
        soybean: "🫘",
        green_gram: "🫘",
        black_gram: "🫘",
        red_gram: "🫘",
        pigeon_pea: "🫘",
        kidney_beans: "🫘",
        peas: "🫛",
        beans: "🫛",
        broad_beans: "🫛",
        cowpea: "🫘",

        // 🥜 Nuts / Seeds
        peanut: "🥜",
        groundnut: "🥜",
        almond: "🥜",
        cashew: "🥜",
        walnut: "🥜",
        pistachio: "🥜",
        sesame: "🌱",
        sunflower_seed: "🌻",
        flaxseed: "🌱",
        mustard: "🌱",
        chia_seed: "🌱",
        hemp_seed: "🌱",

        // 🧅 Vegetables
        onion: "🧅",
        garlic: "🧄",
        potato: "🥔",
        sweet_potato: "🍠",
        cassava: "🍠",
        tapioca: "🍠",
        yam: "🍠",
        tomato: "🍅",
        brinjal: "🍆",
        eggplant: "🍆",
        chilli: "🌶️",
        green_chilli: "🌶️",
        red_chilli: "🌶️",
        capsicum: "🫑",
        green_capsicum: "🫑",
        yellow_capsicum: "🫑",
        red_capsicum: "🫑",
        carrot: "🥕",
        beetroot: "🥕",
        radish: "🥕",
        turnip: "🥕",
        parsnip: "🥕",
        cucumber: "🥒",
        zucchini: "🥒",
        pumpkin: "🎃",
        bottle_gourd: "🥒",
        bitter_gourd: "🥒",
        ridge_gourd: "🥒",
        snake_gourd: "🥒",
        ash_gourd: "🥒",
        ivy_gourd: "🥒",
        cabbage: "🥬",
        red_cabbage: "🥬",
        cauliflower: "🥦",
        broccoli: "🥦",
        spinach: "🥬",
        lettuce: "🥬",
        kale: "🥬",
        bok_choy: "🥬",
        coriander: "🌿",
        mint: "🌿",
        basil: "🌿",
        parsley: "🌿",
        oregano: "🌿",
        thyme: "🌿",
        rosemary: "🌿",
        curry_leaf: "🌿",
        drumstick: "🌿",
        moringa: "🌿",
        mushroom: "🍄",
        oyster_mushroom: "🍄",
        shiitake: "🍄",
        button_mushroom: "🍄",

        // 🍎 Fruits
        apple: "🍎",
        green_apple: "🍏",
        banana: "🍌",
        raw_banana: "🍌",
        mango: "🥭",
        raw_mango: "🥭",
        orange: "🍊",
        sweet_lime: "🍊",
        lemon: "🍋",
        grapes: "🍇",
        watermelon: "🍉",
        muskmelon: "🍈",
        papaya: "🍈",
        pineapple: "🍍",
        pomegranate: "🍎",
        guava: "🍏",
        cherry: "🍒",
        lychee: "🍒",
        rambutan: "🍒",
        strawberry: "🍓",
        blueberry: "🫐",
        blackberry: "🫐",
        cranberry: "🫐",
        pear: "🍐",
        peach: "🍑",
        plum: "🍑",
        apricot: "🍑",
        coconut: "🥥",
        avocado: "🥑",
        kiwi: "🥝",
        dragon_fruit: "🐉",
        jackfruit: "🍈",
        dates: "🌴",
        fig: "🍈",
        olive: "🫒",

        // 🌿 Cash Crops
        cotton: "☁️",
        sugarcane: "🎋",
        tea: "🍃",
        coffee: "☕",
        cocoa: "🍫",
        rubber: "🌳",
        tobacco: "🌿",
        jute: "🪢",

        // 🌱 Herbs / Spices
        turmeric: "🟡",
        ginger: "🫚",
        cardamom: "🌿",
        cinnamon: "🌿",
        clove: "🌿",
        black_pepper: "🌶️",
        cumin: "🌱",
        fennel: "🌱",
        saffron: "🌸",
        vanilla: "🌿",
        lemongrass: "🌿",

        // 🌻 Flowers
        sunflower: "🌻",
        rose: "🌹",
        jasmine: "🌼",
        lotus: "🪷",
        hibiscus: "🌺",
        lavender: "💜",
        tulip: "🌷",
        marigold: "🌼",

        // 🌳 Trees / Plantation
        neem: "🌳",
        bamboo: "🎍",
        palm: "🌴",
        teak: "🌳",
        sandalwood: "🌳",
        eucalyptus: "🌳",

        // 🐄 Animal Products
        milk: "🥛",
        egg: "🥚",
        fish: "🐟",
        chicken: "🍗",
        honey: "🍯"
    };

    if (iconMap[name] == undefined) {
        return '🌱'
    }

    return iconMap[name]
}